const PKM_ALL = {
  kanto: {
    1: { id: 1, nome: "Bulbasaur", immagine: "bulbasaur.png", tipi: ["erba","veleno"], regione: "kanto", stage: 1, bst: 318, evoluzione: { a: 2, in: 2, lv: 16 } },
    2: { id: 2, nome: "Ivysaur", immagine: "ivysaur.png", tipi: ["erba","veleno"], regione: "kanto", stage: 2, bst: 405, evoluzione: { a: 3, in: 3, lv: 32 } },
    3: { id: 3, nome: "Venusaur", immagine: "venusaur.png", tipi: ["erba","veleno"], regione: "kanto", stage: 3, bst: 525, evoluzione: null },
    4: { id: 4, nome: "Charmander", immagine: "charmander.png", tipi: ["fuoco"], regione: "kanto", stage: 1, bst: 309, evoluzione: { a: 5, in: 5, lv: 16 } },
    5: { id: 5, nome: "Charmeleon", immagine: "charmeleon.png", tipi: ["fuoco"], regione: "kanto", stage: 2, bst: 405, evoluzione: { a: 6, in: 6, lv: 36 } },
    6: { id: 6, nome: "Charizard", immagine: "charizard.png", tipi: ["fuoco","volante"], regione: "kanto", stage: 3, bst: 534, evoluzione: null },
    7: { id: 7, nome: "Squirtle", immagine: "squirtle.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 314, evoluzione: { a: 8, in: 8, lv: 16 } },
    8: { id: 8, nome: "Wartortle", immagine: "wartortle.png", tipi: ["acqua"], regione: "kanto", stage: 2, bst: 405, evoluzione: { a: 9, in: 9, lv: 36 } },
    9: { id: 9, nome: "Blastoise", immagine: "blastoise.png", tipi: ["acqua"], regione: "kanto", stage: 3, bst: 530, evoluzione: null },
    10: { id: 10, nome: "Caterpie", immagine: "caterpie.png", tipi: ["coleottero"], regione: "kanto", stage: 1, bst: 195, evoluzione: { a: 11, in: 11, lv: 7 } },
    11: { id: 11, nome: "Metapod", immagine: "metapod.png", tipi: ["coleottero"], regione: "kanto", stage: 2, bst: 205, evoluzione: { a: 12, in: 12, lv: 10 } },
    12: { id: 12, nome: "Butterfree", immagine: "butterfree.png", tipi: ["coleottero","volante"], regione: "kanto", stage: 3, bst: 395, evoluzione: null },
    13: { id: 13, nome: "Weedle", immagine: "weedle.png", tipi: ["coleottero","veleno"], regione: "kanto", stage: 1, bst: 195, evoluzione: { a: 14, in: 14, lv: 7 } },
    14: { id: 14, nome: "Kakuna", immagine: "kakuna.png", tipi: ["coleottero","veleno"], regione: "kanto", stage: 2, bst: 205, evoluzione: { a: 15, in: 15, lv: 10 } },
    15: { id: 15, nome: "Beedrill", immagine: "beedrill.png", tipi: ["coleottero","veleno"], regione: "kanto", stage: 3, bst: 395, evoluzione: null },
    16: { id: 16, nome: "Pidgey", immagine: "pidgey.png", tipi: ["normale","volante"], regione: "kanto", stage: 1, bst: 251, evoluzione: { a: 17, in: 17, lv: 18 } },
    17: { id: 17, nome: "Pidgeotto", immagine: "pidgeotto.png", tipi: ["normale","volante"], regione: "kanto", stage: 2, bst: 349, evoluzione: { a: 18, in: 18, lv: 36 } },
    18: { id: 18, nome: "Pidgeot", immagine: "pidgeot.png", tipi: ["normale","volante"], regione: "kanto", stage: 3, bst: 479, evoluzione: null },
    19: { id: 19, nome: "Rattata", immagine: "rattata.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 253, evoluzione: { a: 20, in: 20, lv: 20 } },
    20: { id: 20, nome: "Raticate", immagine: "raticate.png", tipi: ["normale"], regione: "kanto", stage: 2, bst: 413, evoluzione: null },
    21: { id: 21, nome: "Spearow", immagine: "spearow.png", tipi: ["normale","volante"], regione: "kanto", stage: 1, bst: 262, evoluzione: { a: 22, in: 22, lv: 20 } },
    22: { id: 22, nome: "Fearow", immagine: "fearow.png", tipi: ["normale","volante"], regione: "kanto", stage: 2, bst: 442, evoluzione: null },
    23: { id: 23, nome: "Ekans", immagine: "ekans.png", tipi: ["veleno"], regione: "kanto", stage: 1, bst: 288, evoluzione: { a: 24, in: 24, lv: 22 } },
    24: { id: 24, nome: "Arbok", immagine: "arbok.png", tipi: ["veleno"], regione: "kanto", stage: 2, bst: 448, evoluzione: null },
    25: { id: 25, nome: "Pikachu", immagine: "pikachu.png", tipi: ["elettro"], regione: "kanto", stage: 1, bst: 320, evoluzione: { a: 26, in: 26, lv: 22 } },
    26: { id: 26, nome: "Raichu", immagine: "raichu.png", tipi: ["elettro"], regione: "kanto", stage: 2, bst: 485, evoluzione: null },
    27: { id: 27, nome: "Sandshrew", immagine: "sandshrew.png", tipi: ["terra"], regione: "kanto", stage: 1, bst: 300, evoluzione: { a: 28, in: 28, lv: 22 } },
    28: { id: 28, nome: "Sandslash", immagine: "sandslash.png", tipi: ["terra"], regione: "kanto", stage: 2, bst: 450, evoluzione: null },
    29: { id: 29, nome: "NidoranF", immagine: "nidoran-f.png", tipi: ["veleno"], regione: "kanto", stage: 1, bst: 275, evoluzione: { a: 30, in: 30, lv: 16 } },
    30: { id: 30, nome: "Nidorina", immagine: "nidorina.png", tipi: ["veleno"], regione: "kanto", stage: 2, bst: 365, evoluzione: { a: 31, in: 31, lv: 32 } },
    31: { id: 31, nome: "Nidoqueen", immagine: "nidoqueen.png", tipi: ["veleno","terra"], regione: "kanto", stage: 3, bst: 505, evoluzione: null },
    32: { id: 32, nome: "NidoranM", immagine: "nidoran-m.png", tipi: ["veleno"], regione: "kanto", stage: 1, bst: 273, evoluzione: { a: 33, in: 33, lv: 16 } },
    33: { id: 33, nome: "Nidorino", immagine: "nidorino.png", tipi: ["veleno"], regione: "kanto", stage: 2, bst: 365, evoluzione: { a: 34, in: 34, lv: 32 } },
    34: { id: 34, nome: "Nidoking", immagine: "nidoking.png", tipi: ["veleno","terra"], regione: "kanto", stage: 3, bst: 505, evoluzione: null },
    35: { id: 35, nome: "Clefairy", immagine: "clefairy.png", tipi: ["folletto"], regione: "kanto", stage: 1, bst: 323, evoluzione: { a: 36, in: 36, lv: 30 } },
    36: { id: 36, nome: "Clefable", immagine: "clefable.png", tipi: ["folletto"], regione: "kanto", stage: 2, bst: 483, evoluzione: null },
    37: { id: 37, nome: "Vulpix", immagine: "vulpix.png", tipi: ["fuoco"], regione: "kanto", stage: 1, bst: 299, evoluzione: { a: 38, in: 38, lv: 30 } },
    38: { id: 38, nome: "Ninetales", immagine: "ninetales.png", tipi: ["fuoco"], regione: "kanto", stage: 2, bst: 505, evoluzione: null },
    39: { id: 39, nome: "Jigglypuff", immagine: "jigglypuff.png", tipi: ["normale","folletto"], regione: "kanto", stage: 1, bst: 270, evoluzione: { a: 40, in: 40, lv: 30 } },
    40: { id: 40, nome: "Wigglytuff", immagine: "wigglytuff.png", tipi: ["normale","folletto"], regione: "kanto", stage: 2, bst: 435, evoluzione: null },
    41: { id: 41, nome: "Zubat", immagine: "zubat.png", tipi: ["veleno","volante"], regione: "kanto", stage: 1, bst: 245, evoluzione: { a: 42, in: 42, lv: 22 } },
    42: { id: 42, nome: "Golbat", immagine: "golbat.png", tipi: ["veleno","volante"], regione: "kanto", stage: 2, bst: 455, evoluzione: null },
    43: { id: 43, nome: "Oddish", immagine: "oddish.png", tipi: ["erba","veleno"], regione: "kanto", stage: 1, bst: 320, evoluzione: { a: 44, in: 44, lv: 21 } },
    44: { id: 44, nome: "Gloom", immagine: "gloom.png", tipi: ["erba","veleno"], regione: "kanto", stage: 2, bst: 395, evoluzione: { a: 45, in: 45, lv: 30 } },
    45: { id: 45, nome: "Vileplume", immagine: "vileplume.png", tipi: ["erba","veleno"], regione: "kanto", stage: 3, bst: 490, evoluzione: null },
    46: { id: 46, nome: "Paras", immagine: "paras.png", tipi: ["coleottero","erba"], regione: "kanto", stage: 1, bst: 285, evoluzione: { a: 47, in: 47, lv: 24 } },
    47: { id: 47, nome: "Parasect", immagine: "parasect.png", tipi: ["coleottero","erba"], regione: "kanto", stage: 2, bst: 405, evoluzione: null },
    48: { id: 48, nome: "Venonat", immagine: "venonat.png", tipi: ["coleottero","veleno"], regione: "kanto", stage: 1, bst: 305, evoluzione: { a: 49, in: 49, lv: 31 } },
    49: { id: 49, nome: "Venomoth", immagine: "venomoth.png", tipi: ["coleottero","veleno"], regione: "kanto", stage: 2, bst: 450, evoluzione: null },
    50: { id: 50, nome: "Diglett", immagine: "diglett.png", tipi: ["terra"], regione: "kanto", stage: 1, bst: 265, evoluzione: { a: 51, in: 51, lv: 26 } },
    51: { id: 51, nome: "Dugtrio", immagine: "dugtrio.png", tipi: ["terra"], regione: "kanto", stage: 2, bst: 405, evoluzione: null },
    52: { id: 52, nome: "Meowth", immagine: "meowth.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 290, evoluzione: { a: 53, in: 53, lv: 28 } },
    53: { id: 53, nome: "Persian", immagine: "persian.png", tipi: ["normale"], regione: "kanto", stage: 2, bst: 440, evoluzione: null },
    54: { id: 54, nome: "Psyduck", immagine: "psyduck.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 320, evoluzione: { a: 55, in: 55, lv: 33 } },
    55: { id: 55, nome: "Golduck", immagine: "golduck.png", tipi: ["acqua"], regione: "kanto", stage: 2, bst: 500, evoluzione: null },
    56: { id: 56, nome: "Mankey", immagine: "mankey.png", tipi: ["lotta"], regione: "kanto", stage: 1, bst: 305, evoluzione: { a: 57, in: 57, lv: 28 } },
    57: { id: 57, nome: "Primeape", immagine: "primeape.png", tipi: ["lotta"], regione: "kanto", stage: 2, bst: 455, evoluzione: null },
    58: { id: 58, nome: "Growlithe", immagine: "growlithe.png", tipi: ["fuoco"], regione: "kanto", stage: 1, bst: 350, evoluzione: { a: 59, in: 59, lv: 30 } },
    59: { id: 59, nome: "Arcanine", immagine: "arcanine.png", tipi: ["fuoco"], regione: "kanto", stage: 2, bst: 555, evoluzione: null },
    60: { id: 60, nome: "Poliwag", immagine: "poliwag.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 300, evoluzione: { a: 61, in: 61, lv: 25 } },
    61: { id: 61, nome: "Poliwhirl", immagine: "poliwhirl.png", tipi: ["acqua"], regione: "kanto", stage: 2, bst: 385, evoluzione: { a: 62, in: 62, lv: 35 } },
    62: { id: 62, nome: "Poliwrath", immagine: "poliwrath.png", tipi: ["acqua","lotta"], regione: "kanto", stage: 3, bst: 510, evoluzione: null },
    63: { id: 63, nome: "Abra", immagine: "abra.png", tipi: ["psico"], regione: "kanto", stage: 1, bst: 310, evoluzione: { a: 64, in: 64, lv: 16 } },
    64: { id: 64, nome: "Kadabra", immagine: "kadabra.png", tipi: ["psico"], regione: "kanto", stage: 2, bst: 400, evoluzione: { a: 65, in: 65, lv: 36 } },
    65: { id: 65, nome: "Alakazam", immagine: "alakazam.png", tipi: ["psico"], regione: "kanto", stage: 3, bst: 500, evoluzione: null },
    66: { id: 66, nome: "Machop", immagine: "machop.png", tipi: ["lotta"], regione: "kanto", stage: 1, bst: 305, evoluzione: { a: 67, in: 67, lv: 28 } },
    67: { id: 67, nome: "Machoke", immagine: "machoke.png", tipi: ["lotta"], regione: "kanto", stage: 2, bst: 405, evoluzione: { a: 68, in: 68, lv: 36 } },
    68: { id: 68, nome: "Machamp", immagine: "machamp.png", tipi: ["lotta"], regione: "kanto", stage: 3, bst: 505, evoluzione: null },
    69: { id: 69, nome: "Bellsprout", immagine: "bellsprout.png", tipi: ["erba","veleno"], regione: "kanto", stage: 1, bst: 300, evoluzione: { a: 70, in: 70, lv: 21 } },
    70: { id: 70, nome: "Weepinbell", immagine: "weepinbell.png", tipi: ["erba","veleno"], regione: "kanto", stage: 2, bst: 390, evoluzione: { a: 71, in: 71, lv: 30 } },
    71: { id: 71, nome: "Victreebel", immagine: "victreebel.png", tipi: ["erba","veleno"], regione: "kanto", stage: 3, bst: 490, evoluzione: null },
    72: { id: 72, nome: "Tentacool", immagine: "tentacool.png", tipi: ["acqua","veleno"], regione: "kanto", stage: 1, bst: 335, evoluzione: { a: 73, in: 73, lv: 30 } },
    73: { id: 73, nome: "Tentacruel", immagine: "tentacruel.png", tipi: ["acqua","veleno"], regione: "kanto", stage: 2, bst: 515, evoluzione: null },
    74: { id: 74, nome: "Geodude", immagine: "geodude.png", tipi: ["roccia","terra"], regione: "kanto", stage: 1, bst: 300, evoluzione: { a: 75, in: 75, lv: 25 } },
    75: { id: 75, nome: "Graveler", immagine: "graveler.png", tipi: ["roccia","terra"], regione: "kanto", stage: 2, bst: 390, evoluzione: { a: 76, in: 76, lv: 36 } },
    76: { id: 76, nome: "Golem", immagine: "golem.png", tipi: ["roccia","terra"], regione: "kanto", stage: 3, bst: 495, evoluzione: null },
    77: { id: 77, nome: "Ponyta", immagine: "ponyta.png", tipi: ["fuoco"], regione: "kanto", stage: 1, bst: 410, evoluzione: { a: 78, in: 78, lv: 40 } },
    78: { id: 78, nome: "Rapidash", immagine: "rapidash.png", tipi: ["fuoco"], regione: "kanto", stage: 2, bst: 500, evoluzione: null },
    79: { id: 79, nome: "Slowpoke", immagine: "slowpoke.png", tipi: ["acqua","psico"], regione: "kanto", stage: 1, bst: 315, evoluzione: { a: 80, in: 80, lv: 37 } },
    80: { id: 80, nome: "Slowbro", immagine: "slowbro.png", tipi: ["acqua","psico"], regione: "kanto", stage: 2, bst: 490, evoluzione: null },
    81: { id: 81, nome: "Magnemite", immagine: "magnemite.png", tipi: ["elettro","acciaio"], regione: "kanto", stage: 1, bst: 325, evoluzione: { a: 82, in: 82, lv: 30 } },
    82: { id: 82, nome: "Magneton", immagine: "magneton.png", tipi: ["elettro","acciaio"], regione: "kanto", stage: 2, bst: 465, evoluzione: null },
    83: { id: 83, nome: "Farfetchd", immagine: "farfetchd.png", tipi: ["normale","volante"], regione: "kanto", stage: 1, bst: 377, evoluzione: null },
    84: { id: 84, nome: "Doduo", immagine: "doduo.png", tipi: ["normale","volante"], regione: "kanto", stage: 1, bst: 310, evoluzione: { a: 85, in: 85, lv: 31 } },
    85: { id: 85, nome: "Dodrio", immagine: "dodrio.png", tipi: ["normale","volante"], regione: "kanto", stage: 2, bst: 470, evoluzione: null },
    86: { id: 86, nome: "Seel", immagine: "seel.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 325, evoluzione: { a: 87, in: 87, lv: 34 } },
    87: { id: 87, nome: "Dewgong", immagine: "dewgong.png", tipi: ["acqua","ghiaccio"], regione: "kanto", stage: 2, bst: 475, evoluzione: null },
    88: { id: 88, nome: "Grimer", immagine: "grimer.png", tipi: ["veleno"], regione: "kanto", stage: 1, bst: 325, evoluzione: { a: 89, in: 89, lv: 38 } },
    89: { id: 89, nome: "Muk", immagine: "muk.png", tipi: ["veleno"], regione: "kanto", stage: 2, bst: 500, evoluzione: null },
    90: { id: 90, nome: "Shellder", immagine: "shellder.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 305, evoluzione: { a: 91, in: 91, lv: 30 } },
    91: { id: 91, nome: "Cloyster", immagine: "cloyster.png", tipi: ["acqua","ghiaccio"], regione: "kanto", stage: 2, bst: 525, evoluzione: null },
    92: { id: 92, nome: "Gastly", immagine: "gastly.png", tipi: ["spettro","veleno"], regione: "kanto", stage: 1, bst: 310, evoluzione: { a: 93, in: 93, lv: 25 } },
    93: { id: 93, nome: "Haunter", immagine: "haunter.png", tipi: ["spettro","veleno"], regione: "kanto", stage: 2, bst: 405, evoluzione: { a: 94, in: 94, lv: 40 } },
    94: { id: 94, nome: "Gengar", immagine: "gengar.png", tipi: ["spettro","veleno"], regione: "kanto", stage: 3, bst: 500, evoluzione: null },
    95: { id: 95, nome: "Onix", immagine: "onix.png", tipi: ["roccia","terra"], regione: "kanto", stage: 1, bst: 385, evoluzione: null },
    96: { id: 96, nome: "Drowzee", immagine: "drowzee.png", tipi: ["psico"], regione: "kanto", stage: 1, bst: 328, evoluzione: { a: 97, in: 97, lv: 26 } },
    97: { id: 97, nome: "Hypno", immagine: "hypno.png", tipi: ["psico"], regione: "kanto", stage: 2, bst: 483, evoluzione: null },
    98: { id: 98, nome: "Krabby", immagine: "krabby.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 325, evoluzione: { a: 99, in: 99, lv: 28 } },
    99: { id: 99, nome: "Kingler", immagine: "kingler.png", tipi: ["acqua"], regione: "kanto", stage: 2, bst: 475, evoluzione: null },
    100: { id: 100, nome: "Voltorb", immagine: "voltorb.png", tipi: ["elettro"], regione: "kanto", stage: 1, bst: 330, evoluzione: { a: 101, in: 101, lv: 30 } },
    101: { id: 101, nome: "Electrode", immagine: "electrode.png", tipi: ["elettro"], regione: "kanto", stage: 2, bst: 490, evoluzione: null },
    102: { id: 102, nome: "Exeggcute", immagine: "exeggcute.png", tipi: ["erba","psico"], regione: "kanto", stage: 1, bst: 325, evoluzione: { a: 103, in: 103, lv: 30 } },
    103: { id: 103, nome: "Exeggutor", immagine: "exeggutor.png", tipi: ["erba","psico"], regione: "kanto", stage: 2, bst: 520, evoluzione: null },
    104: { id: 104, nome: "Cubone", immagine: "cubone.png", tipi: ["terra"], regione: "kanto", stage: 1, bst: 320, evoluzione: { a: 105, in: 105, lv: 28 } },
    105: { id: 105, nome: "Marowak", immagine: "marowak.png", tipi: ["terra"], regione: "kanto", stage: 2, bst: 425, evoluzione: null },
    106: { id: 106, nome: "Hitmonlee", immagine: "hitmonlee.png", tipi: ["lotta"], regione: "kanto", stage: 2, bst: 455, evoluzione: null },
    107: { id: 107, nome: "Hitmonchan", immagine: "hitmonchan.png", tipi: ["lotta"], regione: "kanto", stage: 2, bst: 455, evoluzione: null },
    108: { id: 108, nome: "Lickitung", immagine: "lickitung.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 385, evoluzione: null },
    109: { id: 109, nome: "Koffing", immagine: "koffing.png", tipi: ["veleno"], regione: "kanto", stage: 1, bst: 340, evoluzione: { a: 110, in: 110, lv: 35 } },
    110: { id: 110, nome: "Weezing", immagine: "weezing.png", tipi: ["veleno"], regione: "kanto", stage: 2, bst: 490, evoluzione: null },
    111: { id: 111, nome: "Rhyhorn", immagine: "rhyhorn.png", tipi: ["terra","roccia"], regione: "kanto", stage: 1, bst: 345, evoluzione: { a: 112, in: 112, lv: 42 } },
    112: { id: 112, nome: "Rhydon", immagine: "rhydon.png", tipi: ["terra","roccia"], regione: "kanto", stage: 2, bst: 485, evoluzione: null },
    113: { id: 113, nome: "Chansey", immagine: "chansey.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 450, evoluzione: null },
    114: { id: 114, nome: "Tangela", immagine: "tangela.png", tipi: ["erba"], regione: "kanto", stage: 1, bst: 435, evoluzione: null },
    115: { id: 115, nome: "Kangaskhan", immagine: "kangaskhan.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 490, evoluzione: null },
    116: { id: 116, nome: "Horsea", immagine: "horsea.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 295, evoluzione: { a: 117, in: 117, lv: 32 } },
    117: { id: 117, nome: "Seadra", immagine: "seadra.png", tipi: ["acqua"], regione: "kanto", stage: 2, bst: 440, evoluzione: null },
    118: { id: 118, nome: "Goldeen", immagine: "goldeen.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 320, evoluzione: { a: 119, in: 119, lv: 33 } },
    119: { id: 119, nome: "Seaking", immagine: "seaking.png", tipi: ["acqua"], regione: "kanto", stage: 2, bst: 450, evoluzione: null },
    120: { id: 120, nome: "Staryu", immagine: "staryu.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 340, evoluzione: { a: 121, in: 121, lv: 30 } },
    121: { id: 121, nome: "Starmie", immagine: "starmie.png", tipi: ["acqua","psico"], regione: "kanto", stage: 2, bst: 520, evoluzione: null },
    122: { id: 122, nome: "MrMime", immagine: "mr-mime.png", tipi: ["psico","folletto"], regione: "kanto", stage: 1, bst: 460, evoluzione: null },
    123: { id: 123, nome: "Scyther", immagine: "scyther.png", tipi: ["coleottero","volante"], regione: "kanto", stage: 1, bst: 500, evoluzione: null },
    124: { id: 124, nome: "Jynx", immagine: "jynx.png", tipi: ["ghiaccio","psico"], regione: "kanto", stage: 1, bst: 455, evoluzione: null },
    125: { id: 125, nome: "Electabuzz", immagine: "electabuzz.png", tipi: ["elettro"], regione: "kanto", stage: 1, bst: 490, evoluzione: null },
    126: { id: 126, nome: "Magmar", immagine: "magmar.png", tipi: ["fuoco"], regione: "kanto", stage: 1, bst: 495, evoluzione: null },
    127: { id: 127, nome: "Pinsir", immagine: "pinsir.png", tipi: ["coleottero"], regione: "kanto", stage: 1, bst: 500, evoluzione: null },
    128: { id: 128, nome: "Tauros", immagine: "tauros.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 490, evoluzione: null },
    129: { id: 129, nome: "Magikarp", immagine: "magikarp.png", tipi: ["acqua"], regione: "kanto", stage: 1, bst: 200, evoluzione: { a: 130, in: 130, lv: 20 } },
    130: { id: 130, nome: "Gyarados", immagine: "gyarados.png", tipi: ["acqua","volante"], regione: "kanto", stage: 2, bst: 540, evoluzione: null },
    131: { id: 131, nome: "Lapras", immagine: "lapras.png", tipi: ["acqua","ghiaccio"], regione: "kanto", stage: 2, bst: 535, evoluzione: null },
    132: { id: 132, nome: "Ditto", immagine: "ditto.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 288, evoluzione: null },
    133: { id: 133, nome: "Eevee", immagine: "eevee.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 325, evoluzione: { a: 134, in: 134, lv: 25 } },
    134: { id: 134, nome: "Vaporeon", immagine: "vaporeon.png", tipi: ["acqua"], regione: "kanto", stage: 2, bst: 525, evoluzione: null },
    135: { id: 135, nome: "Jolteon", immagine: "jolteon.png", tipi: ["elettro"], regione: "kanto", stage: 2, bst: 525, evoluzione: null },
    136: { id: 136, nome: "Flareon", immagine: "flareon.png", tipi: ["fuoco"], regione: "kanto", stage: 2, bst: 525, evoluzione: null },
    137: { id: 137, nome: "Porygon", immagine: "porygon.png", tipi: ["normale"], regione: "kanto", stage: 1, bst: 395, evoluzione: null },
    138: { id: 138, nome: "Omanyte", immagine: "omanyte.png", tipi: ["roccia","acqua"], regione: "kanto", stage: 1, bst: 355, evoluzione: { a: 139, in: 139, lv: 40 } },
    139: { id: 139, nome: "Omastar", immagine: "omastar.png", tipi: ["roccia","acqua"], regione: "kanto", stage: 2, bst: 495, evoluzione: null },
    140: { id: 140, nome: "Kabuto", immagine: "kabuto.png", tipi: ["roccia","acqua"], regione: "kanto", stage: 1, bst: 355, evoluzione: { a: 141, in: 141, lv: 40 } },
    141: { id: 141, nome: "Kabutops", immagine: "kabutops.png", tipi: ["roccia","acqua"], regione: "kanto", stage: 2, bst: 495, evoluzione: null },
    142: { id: 142, nome: "Aerodactyl", immagine: "aerodactyl.png", tipi: ["roccia","volante"], regione: "kanto", stage: 2, bst: 515, evoluzione: null },
    143: { id: 143, nome: "Snorlax", immagine: "snorlax.png", tipi: ["normale"], regione: "kanto", stage: 2, bst: 540, evoluzione: null },
    144: { id: 144, nome: "Articuno", immagine: "articuno.png", tipi: ["ghiaccio","volante"], regione: "kanto", stage: 3, bst: 580, evoluzione: null },
    145: { id: 145, nome: "Zapdos", immagine: "zapdos.png", tipi: ["elettro","volante"], regione: "kanto", stage: 3, bst: 580, evoluzione: null },
    146: { id: 146, nome: "Moltres", immagine: "moltres.png", tipi: ["fuoco","volante"], regione: "kanto", stage: 3, bst: 580, evoluzione: null },
    147: { id: 147, nome: "Dratini", immagine: "dratini.png", tipi: ["drago"], regione: "kanto", stage: 1, bst: 300, evoluzione: { a: 148, in: 148, lv: 30 } },
    148: { id: 148, nome: "Dragonair", immagine: "dragonair.png", tipi: ["drago"], regione: "kanto", stage: 2, bst: 420, evoluzione: { a: 149, in: 149, lv: 55 } },
    149: { id: 149, nome: "Dragonite", immagine: "dragonite.png", tipi: ["drago","volante"], regione: "kanto", stage: 3, bst: 600, evoluzione: null },
    150: { id: 150, nome: "Mewtwo", immagine: "mewtwo.png", tipi: ["psico"], regione: "kanto", stage: 3, bst: 680, evoluzione: null },
    151: { id: 151, nome: "Mew", immagine: "mew.png", tipi: ["psico"], regione: "kanto", stage: 3, bst: 600, evoluzione: null },
    10001: { id: 10001, nome: "KecleonNegozio", immagine: "kecleon.png", tipi: ["normale"], regione: "speciale", stage: 3, bst: 580, evoluzione: null }
  }
};
// EXPORT CORRETTI
window.PKM_ALL_DATA = PKM_ALL;
window.PKM_ALL = PKM_ALL.kanto;
window.PKM_DB = PKM_ALL.kanto;
window.PokeMisteryRL_PKM_ALL = PKM_ALL;
